import {ObjPrice} from "./ObjPrice";
import {BaggagePrice} from "./BaggagePrice";
import {FullRoute} from "./FullRoute";
import {Stopping} from "./Stopping";
import {BusOption} from "./BusOption";
import {IntercarsPlace} from "./IntercarsPlace";

export interface CommonRoute {
    "SessionRouteId": string,
    "City1": string,
    "City2": string,
    "DepartName": string,
    "ArriveName": string,
    "DateDepart1": string,
    "DateArrive1": string,
    "TimeArrive": string,
    "DateArrive": string,
    "TimeDepart": string,
    "DateDepart": string,
    "DepartDateTime": Date,
    "ArriveDateTime": Date,
    "Hour": string,
    "Minuts": string,
    "FreePlace": number,
    "Price": ObjPrice[],
    "BaggagePrices": BaggagePrice[]
    "BaggageDescription": string,
    "Path": string,
    "Id": string,
    "RouteNumber": string,
    Routes: FullRoute[],
    "Carrier": number,
    "CarrierName": string,
    "CarrierLogo": null,
    "RealCarrierName": string,
    "RealCarrierId": number,
    "RealIsPersonalCarrier": boolean,
    "Delete": string,
    "CountFreePromos": number,
    "MaxDiscountPercent": number,
    "IsSpecialRules": boolean,
    "IsInternationalAbroad": boolean,
    "Platforma": string,
    "Link": string | null,
    AllStops: Stopping[],
    "IsCache": boolean,
    "FullPrice": string | null,
    "IsSocket": boolean,
    "BusId": number | null,
    "BusPlaces": null,
    "FreePlaces": null,
    "AdditionalPlace": number,
    "AddInfo": string,
    "BusOptions":BusOption[],
    FullBusPlaces:IntercarsPlace[],
    "TicketRules": string[],
    "UsedByArtmark": boolean,
    "HasExpressAttr": boolean,
    "HasAnimal": boolean,
    "IsPartnerRoute": boolean,
    "SortPriority": number,
    "AnnylationRules": string,
    "Route": string,
    "HasBonusProgram": boolean
}